// Generated by CoffeeScript 1.3.3
(function() {
  var $, Ajax, Base, Collection, Extend, Include, Model, Singleton, Spine,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __slice = [].slice;

  Spine = this.Spine || require('spine');

  $ = Spine.$;

  Model = Spine.Model;

  Ajax = {
    getURL: function(object) {
      return object && (typeof object.url === "function" ? object.url() : void 0) || object.url;
    },
    enabled: true,
    pending: false,
    requests: [],
    disable: function(callback) {
      if (this.enabled) {
        this.enabled = false;
        try {
          return callback();
        } catch (e) {
          throw e;
        } finally {
          this.enabled = true;
        }
      } else {
        return callback();
      }
    },
    requestNext: function() {
      var nextRequest;
      nextRequest = this.requests.shift();
      if (nextRequest) {
        return this.request(nextRequest);
      } else {
        return this.pending = false;
      }
    },
    request: function(request) {
      var _this = this;
      return $.ajax(request.params).success(request.success).error(request.error).complete(function() {
        return _this.requestNext();
      });
    },
    queue: function(request) {
      if (!this.enabled) {
        return;
      }
      if (this.pending) {
        this.requests.push(request);
      } else {
        if (!(request.params.type === 'GET' && request.params.parallel)) {
          this.pending = true;
        }
        this.request(request);
      }
      return request;
    }
  };

  Base = (function() {

    function Base() {}

    Base.prototype.defaults = {
      contentType: 'application/json',
      dataType: 'json',
      processData: false,
      headers: {
        'X-Requested-With': 'XMLHttpRequest'
      }
    };

    Base.prototype.queue = function(params, defaults, success, error) {
      var request;
      if (success == null) {
        success = [];
      }
      if (error == null) {
        error = [];
      }
      request = {
        params: $.extend({}, this.defaults, defaults, params),
        success: typeof success === 'function' ? [success] : success,
        error: typeof error === 'function' ? [error] : error
      };
      return Ajax.queue(request);
    };

    return Base;

  })();

  Collection = (function(_super) {

    __extends(Collection, _super);

    function Collection(model) {
      this.model = model;
      this.errorResponse = __bind(this.errorResponse, this);

      this.recordsResponse = __bind(this.recordsResponse, this);

    }

    Collection.prototype.find = function(id, params, success) {
      var record;
      if (success == null) {
        success = function() {};
      }
      record = new this.model({
        id: id
      });
      return this.queue(params, {
        type: 'GET',
        url: Ajax.getURL(record),
        parallel: true
      }, [this.recordsResponse, success], [this.errorResponse]);
    };

    Collection.prototype.all = function(params, success) {
      if (success == null) {
        success = function() {};
      }
      return this.queue(params, {
        type: 'GET',
        url: Ajax.getURL(this.model),
        parallel: true
      }, [this.recordsResponse, success], [this.errorResponse]);
    };

    Collection.prototype.fetch = function(params, options) {
      var id,
        _this = this;
      if (params == null) {
        params = {};
      }
      if (options == null) {
        options = {};
      }
      if (id = params.id) {
        delete params.id;
        return this.find(id, params, function(record) {
          return _this.model.refresh(record, options);
        });
      } else {
        return this.all(params, function(records) {
          return _this.model.refresh(records, options);
        });
      }
    };

    Collection.prototype.recordsResponse = function(data, status, xhr) {
      return this.model.trigger('ajaxSuccess', null, status, xhr);
    };

    Collection.prototype.errorResponse = function(xhr, statusText, error) {
      return this.model.trigger('ajaxError', null, xhr, statusText, error);
    };

    return Collection;

  })(Base);

  Singleton = (function(_super) {

    __extends(Singleton, _super);

    function Singleton(record) {
      this.record = record;
      this.errorResponse = __bind(this.errorResponse, this);

      this.recordResponse = __bind(this.recordResponse, this);

      this.model = this.record.constructor;
    }

    Singleton.prototype.reload = function(params, options) {
      return this.queue(params, {
        type: 'GET',
        url: Ajax.getURL(this.record)
      }, this.recordResponse(options), this.errorResponse(options));
    };

    Singleton.prototype.create = function(params, options) {
      return this.queue(params, {
        type: 'POST',
        data: JSON.stringify(this.record),
        url: Ajax.getURL(this.model)
      }, this.recordResponse(options), this.errorResponse(options));
    };

    Singleton.prototype.update = function(params, options) {
      return this.queue(params, {
        type: 'PUT',
        data: JSON.stringify(this.record),
        url: Ajax.getURL(this.record)
      }, this.recordResponse(options), this.errorResponse(options));
    };

    Singleton.prototype.destroy = function(params, options) {
      return this.queue(params, {
        type: 'DELETE',
        url: Ajax.getURL(this.record)
      }, this.recordResponse(options), this.errorResponse(options));
    };

    Singleton.prototype.recordResponse = function(options) {
      var _this = this;
      if (options == null) {
        options = {};
      }
      return function(data, status, xhr) {
        var _ref;
        if (Spine.isBlank(data)) {
          data = false;
        } else {
          data = _this.model.fromJSON(data);
        }
        Ajax.disable(function() {
          if (data) {
            if (data.id && _this.record.id !== data.id) {
              _this.record.changeID(data.id);
            }
            return _this.record.updateAttributes(data.attributes());
          }
        });
        _this.record.trigger('ajaxSuccess', data, status, xhr);
        return (_ref = options.success) != null ? _ref.apply(_this.record) : void 0;
      };
    };

    Singleton.prototype.errorResponse = function(options) {
      var _this = this;
      if (options == null) {
        options = {};
      }
      return function(xhr, statusText, error) {
        var _ref;
        _this.record.trigger('ajaxError', xhr, statusText, error);
        return (_ref = options.error) != null ? _ref.apply(_this.record) : void 0;
      };
    };

    return Singleton;

  })(Base);

  Model.host = '';

  Include = {
    ajax: function() {
      return new Singleton(this);
    },
    url: function() {
      var args, url;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      url = Ajax.getURL(this.constructor);
      if (url.charAt(url.length - 1) !== '/') {
        url += '/';
      }
      url += encodeURIComponent(this.id);
      args.unshift(url);
      return args.join('/');
    }
  };

  Extend = {
    ajax: function() {
      return new Collection(this);
    },
    url: function() {
      var args;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      args.unshift(this.className.toLowerCase() + 's');
      args.unshift(Model.host);
      return args.join('/');
    }
  };

  Model.Ajax = {
    extended: function() {
      this.fetch(this.ajaxFetch);
      this.change(this.ajaxChange);
      this.extend(Extend);
      return this.include(Include);
    },
    ajaxFetch: function() {
      var _ref;
      return (_ref = this.ajax()).fetch.apply(_ref, arguments);
    },
    ajaxChange: function(record, type, options) {
      if (options == null) {
        options = {};
      }
      if (options.ajax === false) {
        return;
      }
      return record.ajax()[type](options.ajax, options);
    }
  };

  Model.Ajax.Methods = {
    extended: function() {
      this.extend(Extend);
      return this.include(Include);
    }
  };

  Ajax.defaults = Base.prototype.defaults;

  Spine.Ajax = Ajax;

  if (typeof module !== "undefined" && module !== null) {
    module.exports = Ajax;
  }

}).call(this);
